kind: pipeline
type: docker
name: multi-platform-build

# 配置运行环境
platform:
  os: linux
  arch: amd64

steps:
  # 步骤2: 构建并推送多平台镜像
  - name: build-and-push
    image: docker:dind
    privileged: true
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - dockerd-entrypoint.sh --dns 192.168.0.10 --insecure-registry 192.168.0.10:5000 &
      - sleep 5
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker pull 192.168.0.10:5000/moby/buildkit:buildx-stable-1
      - docker buildx create --name multiarch --use || true
      - docker buildx inspect --bootstrap
      - |
        docker buildx build \
          --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
          --tag $DOCKER_USERNAME/cowyo:latest \
          --tag $DOCKER_USERNAME/cowyo:${DRONE_COMMIT_SHA:0:8} \
          --push \
          -f cowyo/Dockerfile cowyo/
      - docker buildx rm multiarch || true

# 触发条件
trigger:
  branch:
    - main
    - master
  event:
    - push
    - tag
