kind: pipeline
type: docker
name: default

steps:
  - name: setup qemu
    image: docker/setup-qemu
    privileged: true
    commands:
      - -- platforms=linux/amd64,linux/arm64

  - name: setup buildx
    image: docker/setup-buildx-action
    privileged: true

  - name: login to docker
    image: docker
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - name: build and push
    image: docker
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap
      - docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t $DOCKER_USERNAME/your-image-name:latest -f test/Dockerfile \
          --push \
          test/
