name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo $${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
        docker buildx create --name multiarch --use || true
        docker buildx inspect --bootstrap
        docker buildx build \
          --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
          --tag ${{ env.DOCKER_USERNAME }}/cowyo:latest \
          --tag ${{ env.DOCKER_USERNAME }}/cowyo:${github.sha:0:8} \
          --push \
          -f cowyo/Dockerfile cowyo/
        
        # docker buildx build \
        #   --platform linux/amd64,linux/arm64,linux/arm/v7 \
        #   --tag ${{ env.DOCKER_USERNAME }}/gemini-cli:latest \
        #   --tag ${{ env.DOCKER_USERNAME }}/gemini-cli:${github.sha:0:8} \
        #   --push \
        #   -f gemini-cli/Dockerfile gemini-cli/
        docker buildx rm multiarch || true
